### ISSUE TITLE
 Correction of the ERC paper list

### ISSUE THREAD

**Issue by YunheXIE** [declare-lab/awesome-emotion-recognition-in-conversations#1]
**_Multi-Task Learning Network for Emotion Recognition in Conversation_** and **_Multi-Task Learning with Auxiliary Speaker Identification for Conversational Emotion Recognition_** are two different versions of the same paper. In addition, the former is not included in AAAI2020. Since the latter is a newer version, the latter should be retained and the former should be deleted.

**Comment by soujanyaporia** [comment]
Done
