### ISSUE TITLE
[TYPO] meaningless repeat

### ISSUE THREAD

**Issue by Freed-Wu** [declare-lab/awesome-emotion-recognition-in-conversations#4]
Real-Time Emotion Recognition via Attention Gated Hierarchical Memory Network, AAAI 2020 has been repeated again.
why not sort the result according to time or name in order to reduce the probability of repeat?
thanks.

**Comment by soujanyaporia** [comment]
Thanks for raising this issue. Besides the point you raised, this repo also should be updated with all the latest works. Why don't you spend some time putting a PR? The purpose of this repo was to help the community however we do not really have time to keep updating it on a regular basis. Hope you understand. Thanks.

**Comment by Freed-Wu** [comment]
thanks for your reply!
i am learning some contents which maybe be related to it. if i have enough knowledge about it, i am pleasured to help it.

thanks.
